### ISSUE TITLE
Tag 0.9.5530 missing on hub.docker.com

### ISSUE THREAD

**Issue by whobubble** [pointslope/docker-datomic#2]
Hi,

I tried using the updated image version 0.9.5530 but discovered that the docker-datomic image version needed is only tagged with "latest" on hub.docker.com, not also with the version number (these are all older).
Hence the Dockerfile outlined in the README cannot work, since it calls out the version in the FROM statement:

```
FROM pointslope/datomic-pro-starter:0.9.5530
```

![image](https://cloud.githubusercontent.com/assets/15037/20887978/2c7ae406-bafd-11e6-9f1c-7a9f949be09a.png)

Thanks for adding the tag.
Stefan

**Comment by christianromney** [comment]
Hi @whobubble 
You caught me in the middle of a change that sadly stretched over three days. I'll push the tag out today along with an update to Docker Datomic example. Thanks!

**Comment by christianromney** [comment]
The tag image should be there now. Feel free to pull!
