### ISSUE TITLE
Cannot find ./bin/transactor

### ISSUE THREAD

**Issue by jeremyheiler** [pointslope/docker-datomic#3]
I've copied this Dockerfile locally so I can make changes to it (I need to run `./bin/datomic ensure-transactor`), but before I did, I tried to run it as-is. However, I'm getting this error.

```
ERROR: for datomic  Cannot start service datomic: oci runtime error: container_linux.go:247: starting container process caused "exec: \"./bin/transactor\": stat ./bin/transactor: no such file or directory"
```

I'm rather new to docker, so I'm not sure how to further debug this. The `$DOCKER_HOME` env variable seems to be correct, as per the `echo`.

I don't get this error when I depend on this docker image using `FROM`.

**Comment by jeremyheiler** [comment]
I figured out that it was because of the `ONBUILD` directive. Sorry for the noise.

**Comment by theronic** [comment]
How did you fix this @jeremyheiler? Did you change ONBUILD to RUN?

**Comment by jeremyheiler** [comment]
I’m sorry, I don’t remember.
